package vn.fis.finaltest.constant;

public class Constant {
    public static final String ORDER_NOT_FOUND_EXCEPTION = "ORDER_NOT_FOUND_EXCEPTION";
    public static final String CUSTOMER_NOT_FOUND_EXCEPTION = "CUSTOMER_NOT_FOUND_EXCEPTION";
    public static final String ORDER_ITEM_NOT_FOUND_EXCEPTION = "ORDER_ITEM_NOT_FOUND_EXCEPTION";
    public static final String PRODUCT_QUANTITY_NOT_ENOUGH_EXCEPTION = "PRODUCT_QUANTITY_NOT_ENOUGH_EXCEPTION";
    public static final String PRODUCT_NOT_FOUND_EXCEPTION = "PRODUCT_NOT_FOUND_EXCEPTION";

    public static final String CONVERT_STATUS_CREATED_TO_PAID_EXCEPTION = "CONVERT_STATUS_CREATED_TO_PAID_EXCEPTION";
    public static final String CONVERT_STATUS_CREATED_TO_CANCELLED_EXCEPTION = "CONVERT_STATUS_CREATED_TO_CANCELLED_EXCEPTION";

    public static final String ADD_ORDER_ITEM_EXCEPTION = "ADD_ORDER_ITEM_EXCEPTION";

    public static final String REMOVE_ORDER_ITEM_EXCEPTION = "REMOVE_ORDER_ITEM_EXCEPTION";
    public static final String REMOVE_ORDER_STATUS_EXCEPTION = "REMOVE_ORDER_STATUS_EXCEPTION";

    public static final String CUSTOMER_MOBILE_EXCEPTION = "CUSTOMER_MOBILE_EXCEPTION";
}
